from __future__ import annotations

import customtkinter as ctk

APP_BG = "#F4F7FB"
SURFACE = "#FFFFFF"
SURFACE_ALT = "#EEF3F9"
SURFACE_SOFT = "#E6EDF7"
BORDER = "#D7E1EE"
TEXT = "#162033"
TEXT_MUTED = "#66758D"
PRIMARY = "#1D4ED8"
PRIMARY_HOVER = "#1E40AF"
PRIMARY_SOFT = "#DBEAFE"
ACCENT_PANEL = "#F7FAFD"
ACCENT_PANEL_BORDER = "#D9E4F2"
SEGMENT_BG = "#DCE7F5"
SEGMENT_IDLE = "#F8FBFF"
SEGMENT_IDLE_HOVER = "#EAF1FA"
SEGMENT_TEXT = "#213247"
HINT_TEXT = "#5C6F86"
SCREEN_BG = "#071421"
SCREEN_PANEL = "#0C1B2B"
SCREEN_PANEL_ALT = "#10263A"
SCREEN_GRID = "#1E3850"
SCREEN_TEXT = "#E8F1FB"
SCREEN_MUTED = "#8FA7BF"
SCREEN_BLUE = "#35A2FF"
SCREEN_CYAN = "#39D0FF"
SCREEN_GREEN = "#22C55E"
SCREEN_RED = "#F45B69"
SCREEN_GLOW = "#15324A"
SUCCESS = "#15803D"
SUCCESS_SOFT = "#DCFCE7"
WARNING = "#B45309"
WARNING_SOFT = "#FEF3C7"
DANGER = "#B91C1C"
DANGER_SOFT = "#FEE2E2"
INFO = "#0F766E"
INFO_SOFT = "#CCFBF1"
SHADOW = "#D6DFEB"

FONT_FAMILY = "Microsoft YaHei UI"
FONT_MONO = "Consolas"


def configure_theme() -> None:
    ctk.set_appearance_mode("light")
    ctk.set_default_color_theme("blue")
